from user import *
user = User("","","","","","","","")

print(user)
print(user.User_Name())
print(user.First_Name())
print(user.Sur_Name())
print(user.Street_Name())
print(user.Post_Code())
print(user.Email_Address())
print(user.Date_of_birth())
print(user.Change_first_name())
print(user.Change_email_address())
print(user.Change_date_of_birth())
print(user.Change_sur_name())